---
title: "Methods"
output: html_document
date: "2023-04-11"
---

### Specifications of fixed and variable modifications

The Unimod [@creasydavidm2004] definition of positions and sites were adopted by Mzion for specifying fixed and variable modifications. The value of a position is in one of "Anywhere", "Protein N-term", "Protein C-term", "Any N-term" or "Any C-term". The last two position labels can be shorthanded as "N-term" and "C-term". A site is a one-letter representation of the twenty amino-acid residues, as well as the terminal sites of "N-term" and "C-term". The general format in specifying a fixed or variable modification is `title (position = site)` where title is a unique character string without space. At a position of "Anywhere", the modification can be shorthanded as `title (site)`, for example, `TMT10plex (K)`. For a terminal modification at any site, it can be abbreviated as `title (position)`, for example, `Acetyl (Protein N-term)` and `TMT10plex (N-term)`. There are circumstances that both position and site are needed for specifying a modification, for instance, `Gln->pyro-Glu (N-term = Q)`. More examples are available in the help document of Mzion utility of `parse_unimod`.

*Precursor masses*. Protein entries in FASTA databases were digested *in silico* into peptide sequences according to a full enzymatic specificity, for example tryptic cleavages at C-terminal K or R, at no missed cleavage. Masses of the bare sequences are first obtained by summing over the masses of amino-acid residues therein (temporarily ignore the masses at sites "N-term", "C-term" and the mass deltas by "Anywhere" variable modifications). Rolling sums are then applied to obtain the masses of longer sequences by concatenating adjacent pieces of peptide sequences according to the number of allowed missed cleavages, followed by the capping of "N-term" and "C-term" masses. The full sequences are then filtered by the range of lengths specified in the search. Analogous rolling sums are employed to obtain the masses of peptide sequences over a range of length for searches at NES. For searches with semi-enzyme specificity, the semi-enzyme sequences and their masses are generated by sequential trimmings of residues from the N- or the C-terminals of full sequences. Next the sequences are dispatched according to the attributes of amino-acid look-ups (Supplementary Fig. 12). For instance, when against a look-up with an attribute of "Oxidation (M)", only sequences with residue M are retained.

The base module of the look-ups corresponds to the combination of fixed and variable modifications that were specified originally in a search. Subjected to fixed-to-variable coercions at sites "N-term", "C-term" and "Anywhere", the masses in the base module are compensated accordingly and concluded. The masses of various variable terminals are then capped onto the sequences for the remaining modules (there is only one N- and C-terminal in a peptide sequence and simple summation makes no difference whether the terminal sites are coerced or not). Note that coerced "Anywhere" modifications are reverted back to fixed modifications when possible (*Compilation of fixed and variable modifications*). The precursor masses are thus compensated by the back-coerced "Anywhere" masses accordingly. Finally, combinatorial variable masses of sequences, including neutral losses, are computed to form the space of precursor masses by modules.

The modualized precursor masses are further binned according to the tolerance in mass error. The bin width is half of the size of the tolerance. For instance, at a default precursor mass tolerance of 20 ppm, the theoretical masses are binned at every 10 ppm. Later when matching tandem spectra, +/-20 ppm is the maximum mass error (the maximum distance between two adjacent bins) that can be found between experimentals and theoreticals. Experimental spectra are binned accordingly. Namely, the minimum precursor mass that have been specified in a search is used as the common starting point in the binning. This ensures a one-to-one correspondence of bin indexes between experimentals and theoreticals. Finally, the binned theoretical and experimental precursor masses in the form of neutral masses are stored on disk (and can be reused in a new search at matched search parameters). The decoy sequences are constructed by reversing target peptide sequences with the fixation of both the N- and the C-terminal residues (e.g. PEPTIDE to PDITPEE).

*Tandem spectra matches*. Experimental tandem spectra are matched to theoreticals by modules of fixed and variable modifications. Under each module, the experimental and theoretical spaces are first subset mutually by bins of overlapping precursor masses. Tandem spectra are then generated for the theoretical precursors and the searches traverse through the bins. To avoid combinatorial explosion, the permutation of variable modifications and their sites are modified from the recursion version in R package gtools with "for" loops.

When matching the primary MS2 species (e.g., *b* and *y* ions), both experimental and theoretical MS2 values, $x$, are converted to indexes $\left\lceil \textbf{ln}(x/x_0)/\textbf{ln}(1+d) \right\rceil$ where $x_0$ is the minimum MS2 *m*/*z* supplied in a search and $d$ is a bin width, for example 10 ppm. The experimental and theoretical values with mass difference smaller than $d$ can be off by +/-1 in bin indexes during the numeric-to-integer conversions. Additional matches with 1-increment or decrease of theoretical indexes are carried out. The one-to-one correspondence between experimental and theoretical *m*/*z* values, as well as experimental MS2 intensities, are necessarily maintained. These allow a later enrichment analyses of peptide scores based on the number of matches at descending MS2 ion intensity. Disparity between experimental and theoretical values can occasionally occur due to the numeric-to-integer conversions (for example, multiple experimental indexes match to the same theoretical index). In rare events of this kind, computationally more expensive outer products are performed for matches between the original experimental and theoretical *m*/*z* values.

